apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.19.0-debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - '9999999'
      env:
        - name: AWS_REGION
          value: 'eu-north-1'
        - name: AWS_DEFAULT_REGION
          value: 'eu-north-1'
        - name: AWS_SDK_LOAD_CONFIG
          value: 'true'
  restartPolicy: Never
