apiVersion: v1
kind: Secret
metadata:
  name: repo-github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:ViolinCake/k8s.git

  # generate key pair, put private key here in the secret so it will be used by the image updater
  # put the public key in the github repo key deploy section
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACACwCUQZOWfD2lQfKpOBInVIn7Xl7sfc3S+CFMTYofabQAAAJg27npDNu56
    QwAAAAtzc2gtZWQyNTUxOQAAACACwCUQZOWfD2lQfKpOBInVIn7Xl7sfc3S+CFMTYofabQ
    AAAEDjEhaYPVndcmIcTgK60GK0dXdOQ822Ki3yi08ozvBIbwLAJRBk5Z8PaVB8qk4EidUi
    fteXux9zdL4IUxNih9ptAAAAFWFyZ29jZC1pbWFnZXItdXBkYXRlcg==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
